Dotifle Tmux-mavigator with Alt-l and arrow and lint bashrc and vimrc

diff --git a/dotfile/bashrc b/dotfile/bashrc
--- a/dotfile/bashrc
+++ b/dotfile/bashrc
@@ -3,7 +3,7 @@
   [ -z "$PS1" ] && return
 
   # Goto home
-  if [ $PWD == / ] ; then cd ~ ; fi
+  if [ "$PWD" == / ] ; then cd "$HOME" || : ; fi
 
   # Set OS
   uname=$(uname -a)
@@ -24,7 +24,7 @@
   esac
 
   # Set USER
-  [ -z "$USER" ] && command -v whoami > /dev/null && export USER=$(whoami)
+  [ -z "$USER" ] && command -v whoami > /dev/null && USER=$(whoami) && export USER
 
 # Path
   # Save
@@ -73,23 +73,25 @@
 
 # Execute tmux
   if command -v tmux &> /dev/null && [ -n "$PS1" ] \
+      && [ -z "$TMUX" ] \
       && [[ ! "$TERM" =~ screen ]]  && [[ ! "$TERM" =~ "screen-256color" ]] \
       && [[ ! "$TERM" =~ tmux ]] && [[ ! "$TERM" =~ "tmux-256color" ]] \
-      && [ -z "$TMUX" ]; then
-    exec env TERM=tmux-256color tmux
+      ; then
+    exec env TERM=tmux-256-color tmux
   fi
 
 
 # Unknown command callback (tip: install bash-completion on tmux)
-function command_not_found_handle {
-  # If starting with g : git
-  if [ ${1:0:1} == g ]; then
-    git ${1:1} $2
-  # If any shit, echo bash default errmsg
-  else
-    echo "bash(rc): $1: command not found"
-  fi
-}
+  function command_not_found_handle {
+    # If starting with g : git
+    if [ "${1:0:1}" == "g" ]; then
+      # shellcheck disable=SC2086
+      git "${1:1}" $2
+    # If any shit, echo bash default errmsg
+    else
+      echo "bash(rc): $1: command not found"
+    fi
+  }
 
 
 # Preferences
@@ -99,7 +101,7 @@ function command_not_found_handle {
   stty -ixon
 
   # Vi as default `git commit`
-  EDITOR='vim'
+  export EDITOR='vim'
   # Check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
   shopt -s checkwinsize
 
@@ -133,7 +135,7 @@ function command_not_found_handle {
   export -f parse_title
 
   # Title: Host: CD
-  PS1='\e]0;`parse_title`\007'
+  PS1='\[\e]0;\]`parse_title`\007'
   # CD (green)
   PS1+='\[\e[32m\]\w'
   # Git Branch (yellow)
@@ -184,8 +186,9 @@ function command_not_found_handle {
       . /etc/bash_completion
   fi
 
-  if [ -f $HOME/.bash_aliases.sh ]; then
-      . $HOME/.bash_aliases.sh
+  if [ -f "$HOME/.bash_aliases.sh" ]; then
+    # shellcheck source=/home/tourneboeuf/.bash_aliases.sh
+    source "$HOME/.bash_aliases.sh"
   fi
 
 
@@ -230,7 +233,8 @@ function command_not_found_handle {
 
 # Fast
   # tmux completion
-  source $v/dotfile/tmux_completion.sh
+  # shellcheck source=/home/tourneboeuf/.vim/dotfile/tmux_completion.sh
+  source "$v/dotfile/tmux_completion.sh"
   # man
   export PAGER="vman"
   # complete -cf sudo
@@ -245,18 +249,18 @@ function command_not_found_handle {
 # pip bash completion start
 _pip_completion()
 {
-    COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}" \
-                   COMP_CWORD=$COMP_CWORD \
-                   PIP_AUTO_COMPLETE=1 $1 2>/dev/null ) )
+    mapfile -t COMPREPLY < <( \
+      COMP_WORDS="${COMP_WORDS[*]}" \
+      COMP_CWORD=$COMP_CWORD \
+      PIP_AUTO_COMPLETE=1 $1 2>/dev/null )
 }
 complete -o default -F _pip_completion pip
 # pip bash completion end
 
-[ -f ~/.fzf.bash ] && source ~/.fzf.bash
 
 function myff() { ffmpeg -i "$1"  -f avi -c:v mpeg4 -b:v 4000k -c:a libmp3lame -b:a 320k  "$2" ; }
 function mygif() { ffmpeg  -i "$1" -vf "fps=10,scale=640:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 "$2"; }
 function mymp3() { find . -type f -regex '.*/.*\(webm\|mkv\)' -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -c:a libmp3lame -y "${FILE%.*}.mp3";' _ '{}' \; ; }
 
 
-# vim:sw=2:foldignore=:
+# vim:sw=2:ts=2:foldignore=:
